# Generated by Django 4.2.14 on 2025-04-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0007_humantidesclasssubmission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tidestarget",
            name="auto_tidesclass",
        ),
        migrations.RemoveField(
            model_name="tidestarget",
            name="auto_tidesclass_other",
        ),
        migrations.RemoveField(
            model_name="tidestarget",
            name="auto_tidesclass_prob",
        ),
        migrations.RemoveField(
            model_name="tidestarget",
            name="auto_tidesclass_subclass",
        ),
        migrations.AddField(
            model_name="tidestarget",
            name="auto_tidesclassifications",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Auto TiDES Classifications"
            ),
        ),
    ]
